INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:MC目录已成功写入文件
INFO:root:MC目录已成功写入文件
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
ERROR:root:错误,Python输出:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 831, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 775, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 857, in read_chunked
    self._original_response.close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericsmac/Downloads/Python-Minecraft-Luncher/cmd/./QtGUI/mainwindow.py", line 56, in <module>
    for i in minecraft_launcher_lib.utils.get_available_versions(minecraft_directory):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minecraft_launcher_lib/utils.py", line 74, in get_available_versions
    for i in get_version_list():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minecraft_launcher_lib/utils.py", line 38, in get_version_list
    vlist = get_requests_response_cache("https://launchermeta.mojang.com/mc/game/version_manifest.json").json()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minecraft_launcher_lib/helper.py", line 222, in get_requests_response_cache
    r = requests.get(url, headers={"user-agent": get_user_agent()})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))
---------------
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:MC目录已成功写入文件
INFO:root:MC目录已成功写入文件
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:MC目录已成功写入文件
INFO:root:MC目录已成功写入文件
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:MC目录已成功写入文件
INFO:root:MC目录已成功写入文件
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:下载Minecraft
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
ERROR:root:错误,Python输出:
Traceback (most recent call last):
  File "/Users/ericsmac/Downloads/Python-Minecraft-Luncher/cmd/./QtGUI/mainwindow.py", line 23, in <module>
    with open("./data/directory.pmldatafile","r",encoding="UTF16BE") as rf:
LookupError: unknown encoding: UTF16BE
---------------
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:MC目录已成功写入文件
INFO:root:MC目录已成功写入文件
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
ERROR:root:错误,Python输出:
Traceback (most recent call last):
  File "/Users/ericsmac/Downloads/Python-Minecraft-Luncher/./QtGUI/mainwindow.py", line 57, in <module>
    for i in minecraft_launcher_lib.utils.get_available_versions(minecraft_directory):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minecraft_launcher_lib/utils.py", line 74, in get_available_versions
    for i in get_version_list():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minecraft_launcher_lib/utils.py", line 38, in get_version_list
    vlist = get_requests_response_cache("https://launchermeta.mojang.com/mc/game/version_manifest.json").json()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/minecraft_launcher_lib/helper.py", line 222, in get_requests_response_cache
    r = requests.get(url, headers={"user-agent": get_user_agent()})
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
---------------
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
ERROR:root:错误,Python输出:
Traceback (most recent call last):
  File "/Users/ericsmac/Downloads/Python-Minecraft-Luncher/./QtGUI/mainwindow.py", line 125, in <module>
    app.exec_()
KeyboardInterrupt
---------------
INFO:root:以下为CMD程序提供的日志
INFO:root:以下为GUI程序所提供日志
INFO:root:成功加载MC路径
